# -*- coding: utf-8 -*-
"""analyse_telematics_9th_nov_all_rows_july_august.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OLsLQSWNvRIAzLJHKulW48lu6zCJA4KI
"""

# Cell 1: install package
!pip install missingno --quiet

# Cell 2: imports
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import missingno as msno
from IPython.display import display

# Optional: make plots larger
plt.rcParams['figure.figsize'] = (12, 5)

# select vehicle_summary_aug2025.csv

# Load it into pandas
df = pd.read_csv('/content/vehicle_summary_aug2025.csv')

# Quick basic info
print("Shape:", df.shape)
display(df.head())

print("---- BASIC STRUCTURE ----")
df.info(memory_usage='deep')

print("\n---- BASIC STATS ----")
display(df.describe(include='all').T.head(10))

# Count missing and percentage
missing = df.isna().sum().sort_values(ascending=False)
missing_pct = (missing / len(df) * 100).round(2)
missing_summary = pd.DataFrame({'missing_count': missing, 'missing_pct': missing_pct})
display(missing_summary.head(20))

import matplotlib.pyplot as plt
import missingno as msno

# Make plots larger and cleaner
plt.rcParams.update({
    'figure.figsize': (20, 10),  #  wider
    'axes.titlesize': 18,
    'axes.labelsize': 14
})

# ---- MATRIX PLOT ----
msno.matrix(df, figsize=(20, 10), fontsize=12, sparkline=False)
plt.title("Missing Data Matrix - vehicle_summary_aug2025", fontsize=18, pad=20)
plt.show()

always_null = df.columns[df.isna().all()].tolist()
constant_cols = df.columns[df.nunique(dropna=False) <= 1].tolist()

print("Always Null Columns:", always_null)
print("Constant (same value) Columns:", constant_cols)

# --- Identify always-null and constant columns ---
always_null = df.columns[df.isna().all()].tolist()
constant_cols = df.columns[df.nunique(dropna=False) <= 1].tolist()

print(" Always Null Columns (completely empty):")
for c in always_null:
    print(f"  {c} → all {df[c].isna().sum()} missing ({df.shape[0]} rows)")

print("\n Constant Columns (same value in all rows):")
for c in constant_cols:
    unique_val = df[c].unique()[0] if len(df[c].unique()) > 0 else "N/A"
    print(f"  {c} → constant value: {unique_val}")

# --- Drop them
cols_to_drop = always_null + constant_cols
df_clean = df.drop(columns=cols_to_drop)

print(f"\nDropped {len(cols_to_drop)} columns.")
print("Remaining shape:", df_clean.shape)

import pandas as pd

# Columns identified from my analysis
always_null_cols = [
    'START_LOCATION', 'END_LOCATION', 'MONTH_YEAR'
]

constant_cols = [
    'START_LOCATION', 'END_LOCATION', 'TOTAL_ALERT_COUNT', 'OVERSPEED_INSTANCE_COUNT',
    'OVERSPEED_DISTANCE', 'FUEL_DROP_COUNT', 'RASH_DRIVING_COUNT', 'GEOZONE_DELAY_COUNT',
    'ROUTE_DEVIATION_DISTANCE', 'AVG_NO_OF_PASSENGERS', 'GEOZONE_DELAY_INSTANCE',
    'ROUTE_DEVIATION_INSTANCE', 'MONTH_YEAR', 'NO_OF_VEHICLES_OPERATED', 'AVG_STOP_TIME',
    'GEO_ZONE_DELAY_TOTAL_COUNT', 'GEO_ZONE_DELAY_TOTAL_MIN', 'ROUTE_DEVIATION_TOTAL_COUNT',
    'ROUTE_DEVIATION_TOTAL_KM', 'ROUTE_DEVIATION_TOTAL_MIN', 'TOTAL_PASSENGERS_COUNT',
    'AVG_PASSENGERS_PER_TRIP'
]

# Combine and drop unique ones
drop_cols = list(set(always_null_cols + constant_cols))
df_clean = df.drop(columns=drop_cols)

print(f"Dropped {len(drop_cols)} columns.")
print(f"Remaining shape: {df_clean.shape}")

# Check duplicates based on full rows
full_dupes = df_clean[df_clean.duplicated()]
print(f"Duplicate full rows: {full_dupes.shape[0]}")

# Check for duplicate VEHICLE_IDs (if ID should be unique per record)
dup_vehicle_id = df_clean['VEHICLE_ID'].duplicated().sum()
print(f"Duplicate VEHICLE_ID entries: {dup_vehicle_id}")

#  check VIN_NO uniqueness
if 'VIN_NO' in df_clean.columns:
    dup_vin = df_clean['VIN_NO'].duplicated().sum()
    print(f"Duplicate VIN_NO entries: {dup_vin}")

import numpy as np

# Check for negative/ illogical numeric values
num_cols = df_clean.select_dtypes(include=[np.number]).columns

neg_values = (df_clean[num_cols] < 0).sum()
neg_values = neg_values[neg_values > 0]
print("Columns with negative values:\n", neg_values)

# Example sanity ranges
speed_cols = [c for c in df_clean.columns if 'SPEED' in c.upper()]
if speed_cols:
    print("\nSpeed-related columns and their ranges:")
    for c in speed_cols:
        print(f"{c}: min={df_clean[c].min()}, max={df_clean[c].max()}")

# Odometer checks
odo_cols = [c for c in df_clean.columns if 'ODOMETER' in c.upper()]
if odo_cols:
    print("\nOdometer-related columns and their ranges:")
    for c in odo_cols:
        print(f"{c}: min={df_clean[c].min()}, max={df_clean[c].max()}")

# Check odometer consistency
if {'START_ODOMETER', 'END_ODOMETER'}.issubset(df_clean.columns):
    invalid_odo = df_clean[df_clean['END_ODOMETER'] < df_clean['START_ODOMETER']]
    print(f"Odometer inconsistencies (END < START): {invalid_odo.shape[0]} rows")

# Engine / runtime logic
if {'MOVE_ENGINE_HOURS', 'STOP_ENGINE_HOURS'}.issubset(df_clean.columns):
    df_clean['TOTAL_ENGINE_HOURS'] = df_clean['MOVE_ENGINE_HOURS'] + df_clean['STOP_ENGINE_HOURS']
    over_engine = df_clean[df_clean['TOTAL_ENGINE_HOURS'] > 24]
    print(f"Engine hours > 24 (unrealistic for daily summary): {over_engine.shape[0]} rows")

print("\n=== INTEGRITY CHECK SUMMARY ===")
print(f"Duplicate Rows: {full_dupes.shape[0]}")
print(f"Duplicate VEHICLE_IDs: {dup_vehicle_id}")
print(f"Columns with Negative Values: {len(neg_values)}")
if 'invalid_odo' in locals():
    print(f"Odometer Issues: {invalid_odo.shape[0]}")
if 'over_engine' in locals():
    print(f"Engine Hours > 24h: {over_engine.shape[0]}")

# Records where max speed exceeds 200 km/h
speed_outliers = df_clean[df_clean['MAX_SPEED'] > 200]
print(f"Records with MAX_SPEED > 200 km/h: {speed_outliers.shape[0]}")
speed_outliers.head(6)

# Records with negative hour meter values
hour_meter_neg = df_clean[df_clean['HOUR_METER'] < 0]
print(f"Records with negative HOUR_METER: {hour_meter_neg.shape[0]}")
hour_meter_neg[['VEHICLE_ID', 'HOUR_METER']].head(9)

# Basic summary of engine hours
engine_cols = ['MOVE_ENGINE_HOURS', 'STOP_ENGINE_HOURS']
df_clean[engine_cols].describe()

# Show some sample records with engine hour details
df_clean[['VEHICLE_ID', 'MOVE_ENGINE_HOURS', 'STOP_ENGINE_HOURS']].sample(10)

cols = ['HOUR_METER', 'STOP_ENGINE_HOURS', 'MOVE_ENGINE_HOURS']

for col in cols:
    print(f"\nTop 10 most frequent values for {col}:")
    print(df_clean[col].value_counts().head(10))

# Interpretation of Engine Hour Columns - vehicle_summary_aug2025

# HOUR_METER:
# → 99.8% of records are exactly 0.0
# → Few negative values (e.g., -10942, -284, etc.) are invalid
# Indicates data export or sensor issue; cannot depend on it as-is
# Should be cleaned (remove negatives and zeros before use)

# STOP_ENGINE_HOURS:
# → Most frequent value = 744.0 (3434 vehicles) = 31 days × 24 hours
# → Other frequent values (720, 696, etc.) correspond to partial months


# MOVE_ENGINE_HOURS:
# All values are 0.0
# No usable information; drop this column

# 1. Remove rows with negative HOUR_METER values (invalid readings)
df_clean = df_clean[df_clean['HOUR_METER'] >= 0]

# 2. Remove rows where STOP_ENGINE_HOURS > 744 (more than total hours in August)
df_clean = df_clean[df_clean['STOP_ENGINE_HOURS'] <= 744]



# 5. Optional: remove rows with missing odometer or hour meter if essential for analysis
df_clean = df_clean.dropna(subset=['START_ODOMETER', 'END_ODOMETER'])

# --------------------------------------------
# Step 3. Optional: Drop non-informative columns
# --------------------------------------------
# Since we already dropped constant and fully null columns earlier,
# here we just reconfirm that only meaningful columns (≈86) remain

meaningful_cols = df_clean.columns.tolist()
print(f"Columns retained: {len(meaningful_cols)}")
print("Meaningful columns list:")
print(meaningful_cols)

# Drop non-informative engine-hour related columns
cols_to_drop = ['MOVE_ENGINE_HOURS', 'STOP_ENGINE_HOURS', 'TOTAL_ENGINE_HOURS', 'ENGINE_RUN_MINS']

df_clean = df_clean.drop(columns=cols_to_drop, errors='ignore')

# Display updated column count and names
print(f"Columns retained after dropping engine-hour columns: {df_clean.shape[1]}")
print("Updated meaningful columns list:")
print(df_clean.columns.tolist())

import pandas as pd
import numpy as np

# Select only the relevant subset of columns
cols = ['ID', 'VEHICLE_ID', 'VEHICLE_NO', 'VIN_NO', 'IMEI', 'org_id', 'CUSTOMER_ID', 'DEALER_ORG_ID', 'REGION_ID',
        'RESELLER_ORG_ID', 'CREATED_DATE', 'MODIFY_DATE', 'START_ODOMETER', 'END_ODOMETER', 'DISTANCE_TRAVELED',
        'START_HRLFC', 'END_HRLFC', 'FUEL_CONSUMED', 'FUEL_ECONOMY', 'IDLE_MINS', 'MOVE_MINS', 'STOP_MINS',
        'OFFLINE_MINS', 'WORKING_MINS', 'BREAKER_MINS', 'IDLE_ENGINE_HOURS', 'MAX_SPEED', 'AVG_SPEED',
        'SPEED_ALERT_COUNT', 'GEO_ALERT_COUNT', 'IDLE_ALERT_COUNT', 'IDLE_AC_ALERT_COUNT', 'IGN_ALERT_COUNT',
        'MPR_ALERT_COUNT', 'FUEL_ALERT_COUNT', 'HARSH_ALERT_COUNT', 'COOLANT_TEMP_ALERT_COUNT',
        'OIL_PRESURE_ALERT_COUNT', 'ENGINE_SPEED_ALERT_COUNT', 'IMPACT_ALERT_COUNT', 'OVER_STEERING_ALERT_COUNT',
        'SERVICE_ALERT_COUNT', 'SIM_REMOVAL_ALERT_COUNT', 'TAMPER_ALERT_COUNT', 'HARSH_ACC_ALERT_COUNT',
        'HARSH_BRAKE_ALERT_COUNT', 'OVER_SPEED_COUNT', 'OVER_SPEED_DURATION', 'MAX_RPM', 'MAX_RPM_COOL_TEMP',
        'MAX_OIL_PRESSURE', 'MAX_ENG_COOLANT_TEMP', 'MAX_HYDRAULIC_OIL_TEMP', 'START_HOURMETER', 'END_HOURMETER',
        'HOUR_METER', 'NO_OF_TRIPS', 'AVG_TRIPS_PER_DAY', 'AVG_DISTANCE', 'AVG_RUN_TIME', 'AVG_IDLE_TIME',
        'AVG_FUEL_CONSUMED', 'NO_RUN_DAYS', 'MONTH_IN_SERVICE', 'IS_CAN_ENABLED', 'AVG_ENGINE_RUN_TIME',
        'AVG_ENGINE_IDLE_TIME', 'AVG_ENGINE_STOP_TIME', 'RASH_TURNING_COUNT', 'OVER_TIME_DISTANCE_TRAVELLED',
        'OVER_TIME_IDLE_MINS', 'OVER_TIME_MOVE_MINS', 'OVER_TIME_STOP_MINS', 'OVER_TIME_OFFLINE_MINS',
        'WORKING_DISTANCE_TRAVELLED', 'WORKING_IDLE_MINS', 'WORKING_MOVE_MINS', 'WORKING_STOP_MINS',
        'WORKING_OFFLINE_MINS', 'START_GPS_HOURMETER', 'END_GPS_HOURMETER', 'TOTAL_CAN_HOURMETER']

df_sub = df_clean[cols].copy()

# Calculate missingness
missing_pct = df_sub.isna().mean() * 100

# Calculate zeros
zero_pct = (df_sub == 0).mean() * 100

# Identify constant columns (no variation)
constant_cols = [col for col in df_sub.columns if df_sub[col].nunique(dropna=True) == 1]
constant_pct = pd.Series(0, index=df_sub.columns)
constant_pct[constant_cols] = 100

# Combine into a summary DataFrame
data_quality_summary = pd.DataFrame({
    'Missing_%': missing_pct.round(2),
    'Zero_%': zero_pct.round(2),
    'Constant_%': constant_pct
})

# Add total "information loss" metric
data_quality_summary['Total_%'] = data_quality_summary[['Missing_%', 'Zero_%', 'Constant_%']].sum(axis=1)

# Sort descending by Total_% to find top problematic columns
top50_issues = data_quality_summary.sort_values(by='Total_%', ascending=False).head(50)

# Show results
top50_issues

# Step 1: Filter columns with acceptable data quality (Total_% <= 50%)
informative_cols = data_quality_summary[data_quality_summary['Total_%'] <= 50].index.tolist()

# Step 2: Create a cleaned DataFrame with only informative columns
df_final = df_sub[informative_cols].copy()

# Step 3: Identify and log removed columns
removed_cols = data_quality_summary[data_quality_summary['Total_%'] > 50].copy()
removed_cols = removed_cols.sort_values(by='Total_%', ascending=False)

print(f" Final dataset shape: {df_final.shape}")
print(f" Dropped {removed_cols.shape[0]} columns due to high missing/zero/constant rates")

# Display all removed columns with their % metrics
removed_cols[['Missing_%', 'Zero_%', 'Constant_%', 'Total_%']].round(2)

# Filter only the columns that were kept (informative ones)
kept_cols_summary = data_quality_summary.loc[informative_cols].copy()

# Sort descending by Total_% for better visibility
kept_cols_summary = kept_cols_summary.sort_values(by='Total_%', ascending=False)

# Display the kept columns with all metrics
kept_cols_summary[['Missing_%', 'Zero_%', 'Constant_%', 'Total_%']].round(2)

a=df_final.columns.to_list()

print(a)

leng=len(a)
print(leng)

recorded_fields = [
    'ID',                     # System-generated unique record ID
    'VEHICLE_ID',             # Vehicle reference from system
    'VEHICLE_NO',             # Vehicle registration number
    'VIN_NO',                 # Vehicle Identification Number
    'IMEI',                   # Device unique ID (telemetry hardware)
    'org_id', 'CUSTOMER_ID', 'DEALER_ORG_ID', 'REGION_ID', 'RESELLER_ORG_ID',  # Organizational metadata
    'CREATED_DATE', 'MODIFY_DATE',  # Timestamps for record creation/modification
    'START_ODOMETER', 'END_ODOMETER',  # Raw odometer readings
    'IDLE_MINS', 'MOVE_MINS', 'STOP_MINS', 'OFFLINE_MINS',  # Time counters logged directly by device
    'MAX_SPEED', 'AVG_SPEED',  # Speed readings computed internally by ECU/telematics
    'IGN_ALERT_COUNT', 'COOLANT_TEMP_ALERT_COUNT',  # Alert counts triggered from sensors
    'OVER_SPEED_COUNT', 'OVER_SPEED_DURATION',  # Overspeed alerts directly measured
    'MAX_RPM', 'MAX_RPM_COOL_TEMP'  # Peak engine metrics recorded during trips
]

calculated_fields = [
    'DISTANCE_TRAVELED',      # Derived from END_ODOMETER - START_ODOMETER
    'NO_OF_TRIPS',            # Aggregated trip count within period
    'AVG_TRIPS_PER_DAY',      # Computed from total trips / number of days
    'AVG_DISTANCE',           # Derived mean trip distance
    'AVG_RUN_TIME',           # Average duration vehicle was running
    'AVG_IDLE_TIME',          # Average idle time derived from IDLE_MINS
    'NO_RUN_DAYS',            # Count of days with zero trips or movement
    'MONTH_IN_SERVICE',       # Derived from vehicle's service duration
    'AVG_ENGINE_STOP_TIME'    # Derived average time engine was off
]

# Identifier fields (vehicle, device, organizational, and record-level identifiers)
identifier_fields = [
    'ID', 'VEHICLE_ID', 'VEHICLE_NO', 'VIN_NO', 'IMEI',
    'org_id', 'CUSTOMER_ID', 'DEALER_ORG_ID', 'REGION_ID', 'RESELLER_ORG_ID',
    'CREATED_DATE', 'MODIFY_DATE'
]

print (len(identifier_fields), len(recorded_fields), len(calculated_fields))

df_final.head(15).to_csv('15_left_35.csv')



import pandas as pd
import numpy as np

df = df_final.copy()

# Ensure date parsing
df['CREATED_DATE'] = pd.to_datetime(df['CREATED_DATE'])

# Days in the reporting month taken from CREATED_DATE month
df['total_days'] = df['CREATED_DATE'].dt.daysinmonth

# Active days = total days in month minus NO_RUN_DAYS
df['active_days'] = df['total_days'] - df['NO_RUN_DAYS']

# 1. Computed Odometer-based distance
df['computed_distance'] = df['END_ODOMETER'] - df['START_ODOMETER']
df['delta_distance_vs_recorded'] = df['DISTANCE_TRAVELED'] - df['computed_distance']

# 2. Expected derived metrics based on recorded values
df['exp_AVG_TRIPS_PER_DAY'] = np.where(df['active_days'] > 0,
                                       df['NO_OF_TRIPS'] / df['active_days'], np.nan)

df['exp_AVG_DISTANCE'] = np.where(df['active_days'] > 0,
                                  df['DISTANCE_TRAVELED'] / df['active_days'], np.nan)

df['exp_AVG_RUN_TIME'] = np.where(df['active_days'] > 0,
                                  df['MOVE_MINS'] / df['active_days'], np.nan)

# AVG_IDLE_TIME uses total calendar days (confirmed in your dataset)
df['exp_AVG_IDLE_TIME'] = df['IDLE_MINS'] / df['total_days']

# 3. Delta differences between stored and recomputed values
df['delta_AVG_TRIPS_PER_DAY'] = df['AVG_TRIPS_PER_DAY'] - df['exp_AVG_TRIPS_PER_DAY']
df['delta_AVG_DISTANCE'] = df['AVG_DISTANCE'] - df['exp_AVG_DISTANCE']
df['delta_AVG_RUN_TIME'] = df['AVG_RUN_TIME'] - df['exp_AVG_RUN_TIME']
df['delta_AVG_IDLE_TIME'] = df['AVG_IDLE_TIME'] - df['exp_AVG_IDLE_TIME']

# Select columns for review
verification_df = df[
    [
        'VEHICLE_NO',
        'DISTANCE_TRAVELED', 'computed_distance', 'delta_distance_vs_recorded',
        'AVG_TRIPS_PER_DAY', 'exp_AVG_TRIPS_PER_DAY', 'delta_AVG_TRIPS_PER_DAY',
        'AVG_DISTANCE', 'exp_AVG_DISTANCE', 'delta_AVG_DISTANCE',
        'AVG_RUN_TIME', 'exp_AVG_RUN_TIME', 'delta_AVG_RUN_TIME',
        'AVG_IDLE_TIME', 'exp_AVG_IDLE_TIME', 'delta_AVG_IDLE_TIME'
    ]
]

print(verification_df.head(20))

# ------------------------------------------------------------------------------
# Formulas for Derived Telematics Metrics
# ------------------------------------------------------------------------------

# total_days:
#   Number of calendar days in the reporting month
#   Derived from CREATED_DATE as CREATED_DATE.dt.daysinmonth

# active_days:
#   Number of days the vehicle was operational (ran at least once)
#   active_days = total_days - NO_RUN_DAYS

# DISTANCE_TRAVELED:
#   Common assumption = END_ODOMETER - START_ODOMETER
#   Observation from data: This is not true here.
#   DISTANCE_TRAVELED is recorded from telemetry (GPS/ECU aggregation),
#   not calculated from odometer in df_final.

# NO_OF_TRIPS:
#   Recorded aggregated trip count from the telemetry system.
#   Cannot be recomputed from summary data alone.

# AVG_TRIPS_PER_DAY:
#   Formula: NO_OF_TRIPS / active_days
#   Matches consistently in your dataset.

# AVG_DISTANCE:
#   Expected: DISTANCE_TRAVELED / active_days
#   Observation: Does not match consistently.
#   Indicates a different divisor is used in source system,
#   likely counting only days with valid driving activity.
#   Therefore, AVG_DISTANCE derivation in df_final does not match
#   the expected formula based on active_days.

# AVG_RUN_TIME:
#   Formula: MOVE_MINS / active_days
#   Matches consistently in your dataset.

# AVG_IDLE_TIME:
#   Formula: IDLE_MINS / total_days
#   Matches consistently in your dataset.

# NO_RUN_DAYS:
#   Recorded value representing number of days with zero driving activity.
#   Used to compute active_days but not derived here.

# MONTH_IN_SERVICE:
#   Represents number of months vehicle has been in service.
#   Requires in-service/installation date (not present in df_final).
#   Cannot be validated with current dataframe.

# AVG_ENGINE_STOP_TIME:
#   Does not match STOP_MINS / total_days or STOP_MINS / active_days.
#   Indicates dependency on event-level stop segmentation,
#   which is not available in df_final.
#   Cannot be validated with current dataframe.

# ------------------------------------------------------------------------------
# Summary of Validation
# ------------------------------------------------------------------------------

# Correctly Computed in df_final:
#   AVG_TRIPS_PER_DAY = NO_OF_TRIPS / active_days
#   AVG_RUN_TIME      = MOVE_MINS / active_days
#   AVG_IDLE_TIME     = IDLE_MINS / total_days

# Not Matching Expected Formula:
#   AVG_DISTANCE      (source system uses a different day count or filter)
#   DISTANCE_TRAVELED (not derived from odometer, comes from telemetry)
#   AVG_ENGINE_STOP_TIME (requires stop-event detail)

# Recorded / Not Derived in the Dataset:
#   DISTANCE_TRAVELED
#   NO_OF_TRIPS
#   NO_RUN_DAYS
#   MONTH_IN_SERVICE

# ------------------------------------------------------------------------------
# Recorded Fields Associated With Each Derived Field
# ------------------------------------------------------------------------------

# AVG_TRIPS_PER_DAY  ->  NO_OF_TRIPS, NO_RUN_DAYS, CREATED_DATE
# AVG_DISTANCE       ->  DISTANCE_TRAVELED, NO_RUN_DAYS, CREATED_DATE (plus hidden driving-day logic)
# AVG_RUN_TIME       ->  MOVE_MINS, NO_RUN_DAYS, CREATED_DATE
# AVG_IDLE_TIME      ->  IDLE_MINS, CREATED_DATE
# MONTH_IN_SERVICE   ->  MODIFY_DATE + external installation date (not in df_final)
# AVG_ENGINE_STOP_TIME -> STOP_MINS + event-level stop breakdown (not in df_final)

# ------------------------------------------------------------------------------

# Describe the distribution of delta fields and generate summary statistics

# Summary stats for each delta field
delta_fields = [
    'delta_distance_vs_recorded',
    'delta_AVG_TRIPS_PER_DAY',
    'delta_AVG_DISTANCE',
    'delta_AVG_RUN_TIME',
    'delta_AVG_IDLE_TIME'
]

print("\n=== Summary Statistics for Delta Fields ===")
print(df[delta_fields].describe())

# Count how many rows have near-zero delta (matching), small deviation, and large deviation
def categorize_delta(series, tolerance=1e-3):
    return pd.cut(
        series.abs(),
        bins=[0, tolerance, 1, 10, 100, np.inf],
        labels=["Exact/Very Close", "<=1", "<=10", "<=100", ">100"]
    ).value_counts()

print("\n=== Delta Distribution Categories ===")
for col in delta_fields:
    print(f"\nDistribution for {col}:")
    print(categorize_delta(df[col].fillna(0)))

# Optional: Identify top mismatches for manual review
print("\n=== Top delta mismatches for AVG_DISTANCE ===")
print(df[['VEHICLE_NO', 'AVG_DISTANCE', 'exp_AVG_DISTANCE', 'delta_AVG_DISTANCE']]
      .sort_values(by='delta_AVG_DISTANCE', ascending=False)
      .head(10))

print("\n=== Top delta mismatches for DISTANCE_TRAVELED ===")
print(df[['VEHICLE_NO', 'DISTANCE_TRAVELED', 'computed_distance', 'delta_distance_vs_recorded']]
      .sort_values(by='delta_distance_vs_recorded', ascending=False)
      .head(10))

# ------------------------------------------------------------------------------
# Key Inferences
# ------------------------------------------------------------------------------

# DISTANCE_TRAVELED:
# - Not derived from (END_ODOMETER - START_ODOMETER).


# AVG_TRIPS_PER_DAY:
#   Correct and consistent.
#   Formula: NO_OF_TRIPS / (total_days - NO_RUN_DAYS)

# AVG_RUN_TIME:
#   Correct and consistent.
#   Formula: MOVE_MINS / (total_days - NO_RUN_DAYS)

# AVG_IDLE_TIME:
#   Correct and consistent.
#   Formula: IDLE_MINS / total_days   (uses full calendar days)

# AVG_DISTANCE:
#   NOT following expected formula.
#   Expected: DISTANCE_TRAVELED / (total_days - NO_RUN_DAYS)

# MONTH_IN_SERVICE, AVG_ENGINE_STOP_TIME:
#   Cannot be verified — require external install date / event-level stop data.


# ------------------------------------------------------------------------------
# Delta Distributions (Observed Error/Deviation Scales)
# ------------------------------------------------------------------------------

# delta_distance_vs_recorded (DISTANCE vs ODOMETER-based)
#   ~35 rows: exact/very close
#   ~441 rows: within ±1
#   ~1946 rows: within ±10
#   ~1928 rows: within ±100
#   ~623 rows: >100 (significant telemetry-odometer divergence)

# delta_AVG_TRIPS_PER_DAY
#   ~3918 rows match exactly (negligible differences)
#   Calculation confirmed valid.

# delta_AVG_RUN_TIME
#   ~3992 rows match exactly (negligible differences)
#   Calculation confirmed valid.

# delta_AVG_IDLE_TIME
#   ~4511 rows match exactly (negligible differences)
#   Calculation confirmed valid.

# delta_AVG_DISTANCE (largest inconsistency)
#   ~3336 rows: within ±1 (small deviation)
#   ~1334 rows: within ±10
#   ~178 rows: within ±100
#   ~82 rows: >100 (major misalignment)
#   Indicates AVG_DISTANCE uses a different divisor than active_days.

# ------------------------------------------------------------------------------